### ISSUE TITLE
Is there a way to access the root state in a reducer? 

### ISSUE THREAD

**Issue by kaminski** [spierala/mini-rx-store#182]
Is there any way to access the root state in a reducer? This would be to read data, not to manipulate the state beyond the reducer's scope. 

In our use case, we need to look up values in a map, stored in a different branch of the root-state.

**Comment by spierala** [comment]
Hey @kaminski ,

You can access root state in Meta Reducers. Read more about Meta Reducers in the docs: https://mini-rx.io/docs/redux-setup#meta-reducers

If it is just about reading root state you can also use `store.select`: https://mini-rx.io/docs/selectors

I hope that helps!

**Comment by kaminski** [comment]
Thanks!

I had something different in mind, but of course you are right, I could decorate the action object in the meta-reducer with whatever part of the root state is needed for lookups.
