### ISSUE TITLE
Edit Items which have been subscribed to

### ISSUE THREAD

**Issue by theSilverFisch** [spierala/mini-rx-store#189]
I'd like to have a possibility to edit an item before it gets passed into the 
```
.select(state=> state.data['myItemId']).subscribe(myItem => {})
```
callback function after I selected it from the store. Is there a way to see what items are currently subscribed too? Or is there a way hook into 'subscribe' to edit 'myItem' I subscribed to before it get's passed into my subscribe callback?

**Comment by spierala** [comment]
Normally the `select` callback is the place to transform selected data.

In your example callback `state=> state.data['myItemId']`, you are already transforming state to something else.

You can further transform in the select:

```ts
store.select(state => {
    const myItemId = state.data['myItemId'];
    return 'prefix_' + myItemId; // Map to whatever you want
}).subscribe(prefixedItemId => console.log(prefixedItemId)) // subscribe will get the mapped value
```

FYI `select` uses RxJS `map` internally. Therefore `select` is the preferred place to map your data.

**Comment by theSilverFisch** [comment]
> 

I would like to update all items by the same function when they get selected. I need to identify dataItems which are subscribed too by setting them a new attribute containing a timestamp from the moment they got subscribed to so that another script can act as a garbage collector to remove currently unused items from the store -> the minirx store contains a "data" store which acts as a cache for our dataItems which are stored in the indexDB of the browser to prevent performance issues when having >30k dataItems

Would you know a good place to implement this genericly without having to call that timestamp function in each .select I use in my application? And wouldn't I have to send another store dispatch in the select to actually change attributes of the item for all future subscriber functions as well?

Regards

**Comment by spierala** [comment]
@theSilverFisch, did one of the solutions work?

Can I close this issue?
