### ISSUE TITLE
Production usage 

### ISSUE THREAD

**Issue by marcpearson** [spierala/mini-rx-store#79]
I have to start several new projects... Can I use Mini-RX-store in production and be sure to make the right choice?. Development seems to have been interrupted for a few months. Thanks in advance...

**Comment by spierala** [comment]
Hi @marcpearson, you can definitely use MiniRx in production. MiniRx is actively developed. Currently I work on the refactor to NX workspace (see this issue: https://github.com/spierala/mini-rx-store/issues/67)

I strongly believe that MiniRx is the right choice (especially in Angular and Svelte). See here my comparison with Akita and Component Store: https://dev.to/this-is-angular/minirx-feature-store-vs-ngrx-component-store-vs-akita-4983

Please let me know if I can further help you.
